### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by terhechte** [Zewo/Aeon#1]
I couldn't get this to work, so I tried running the Command Line Application from the project. When I do that, and then try `ab` I get the following:

```
b -n 12800 -c 128 http://localhost:8080/
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
apr_socket_recv: Connection refused (61)
```

When I run with `curl http://localhost:8080` it just hangs.

**Comment by terhechte** [comment]
Hm, I'm having the same issue with the Taylor Webserver. Maybe this is because I'm on Yosemite on this system. Other web servers (Python, Ruby, etc) work fine though. I also tried various ports.

**Comment by paulofaria** [comment]
I had problems running the command line in debug mode. Changing it to release does the trick. I shared the command line application scheme with the release configuration and pushed to master. See if it works.

**Comment by paulofaria** [comment]
Can I close this issue?

**Comment by terhechte** [comment]
Sorry for the delay! I was busy working on a different project. Yeah that works.
Thanks!
