### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [Zewo/Aeon#6]
<img width="325" alt="screen shot 2016-02-18 at 8 50 05 am" src="https://cloud.githubusercontent.com/assets/6511079/13150925/a4a16548-d61c-11e5-9225-d1f87c698bfe.png">
Should have this under title:

> Aeon is a GCD based HTTP server for Swift 2.

**Comment by unnamedd** [comment]
We are creating the README and documentations, as soon as we can, all repos will have all information about it.

thank you

**Comment by lfarah** [comment]
Let me know if you need help!
